# fly.toml file generated for saiki on 2022-10-09T23:05:20-04:00

app = "saiki"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
